# Generated by Django 2.2.5 on 2019-09-16 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtor',
            name='photo_main',
        ),
    ]
